apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: dev
  labels:
    app: webapi
    component: backend
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: webapi
    component: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  sessionAffinity: None
